#' Plot discriminant features as Group × Feature heatmap
#'
#' This heatmap summarizes, for each group level (e.g., Depth),
#' the percentage of MAGs where each discriminant feature is present
#' (presence defined as Abundance > 0).
#'
#' This function is robust to an empty `tibble_disc` because it uses
#' `disc_obj$mat_counts` (generated by the discriminant pipeline).
#' @param feature_col ...
#' @param disc_obj Object stored as attr(, "rbims_disc") from get_subset_discriminant().
#' @param metadata Metadata table with columns `Bin_name` and `group_col`.
#' @param group_col Grouping variable in metadata (e.g. "Depth").
#' @param top_n Number of top features to display (ranked by consensus score).
#'
#' @return A ggplot object.
#' @export
plot_disc_heatmap <- function(disc_obj,
                              metadata,
                              group_col,
                              feature_col = "KO",
                              top_n = 40) {
  
  stopifnot(!is.null(disc_obj))
  stopifnot(!is.null(disc_obj$consensus))
  
  # 1) Select top features by score
  top_features <- disc_obj$consensus %>%
    dplyr::arrange(dplyr::desc(.data$score),
                   dplyr::desc(abs(.data$effect)),
                   dplyr::desc(.data$rf_importance)) %>%
    dplyr::slice_head(n = top_n) %>%
    dplyr::pull(.data$feature)
  
  # 2) Long table feature–MAG–abundance
  prof_long <- disc_obj$mat_counts %>%
    tibble::as_tibble(rownames = feature_col) %>%
    dplyr::filter(.data[[feature_col]] %in% top_features) %>%
    tidyr::pivot_longer(
      cols      = -dplyr::all_of(feature_col),
      names_to  = "Bin_name",
      values_to = "Abundance"
    ) %>%
    dplyr::left_join(
      metadata %>% dplyr::select(.data$Bin_name, dplyr::all_of(group_col)),
      by = "Bin_name"
    )
  
  # 3) Summarise % of MAGs with the feature in each group
  group_summary <- prof_long %>%
    dplyr::group_by(.data[[feature_col]], .data[[group_col]]) %>%
    dplyr::summarise(
      n_MAGs    = dplyr::n(),
      n_present = sum(.data$Abundance > 0, na.rm = TRUE),
      freq_MAGs = 100 * .data$n_present / .data$n_MAGs,
      .groups = "drop"
    ) %>%
    dplyr::group_by(.data[[feature_col]]) %>%
    dplyr::mutate(
      ord = mean(.data$freq_MAGs, na.rm = TRUE)
    ) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(
      feature_ord = forcats::fct_reorder(.data[[feature_col]], .data$ord)
    )
  
  ggplot2::ggplot(
    group_summary,
    ggplot2::aes(
      x = .data[[group_col]],
      y = .data$feature_ord,
      fill = .data$freq_MAGs
    )
  ) +
    ggplot2::geom_tile() +
    ggplot2::scale_fill_gradient(
      name = "% MAGs with feature",
      low  = "white",
      high = "steelblue"
    ) +
    ggplot2::labs(x = NULL, y = feature_col) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1),
      panel.grid  = ggplot2::element_blank()
    )
}
